services:
  - type: web
    name: synapse-virtual-ia
    runtime: python

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: MYSQL_HOST
        sync: false

      - key: MYSQL_PORT
        sync: false

      - key: MYSQL_USER
        sync: false

      - key: MYSQL_PASSWORD
        sync: false

      - key: MYSQL_DB
        sync: false

      - key: MYSQL_CHARSET
        value: utf8mb4

      - key: MAIL_SERVER
        sync: false

      - key: MAIL_PORT
        value: "587"

      - key: MAIL_USE_TLS
        value: "True"

      - key: MAIL_USE_SSL
        value: "False"

      - key: MAIL_USERNAME
        sync: false

      - key: MAIL_PASSWORD
        sync: false

      - key: MAIL_DEFAULT_SENDER
        sync: false

      - key: GEMINI_API_KEY
        sync: false

      - key: HUGGINGFACE_TOKEN
        sync: false

      - key: DEEPSEEK_API_KEY
        sync: false

      - key: IA_PROVIDER
        value: huggingface

      - key: PYTHON_VERSION
        value: 3.10.12
